import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!

export const supabase = createClient(supabaseUrl, supabaseAnonKey)

// Database schema for Supabase
export const SUPABASE_SCHEMA = {
  products: {
    table: 'products',
    columns: {
      id: 'id',
      name_ar: 'name_ar',
      barcode: 'barcode',
      category: 'category',
      wholesale_price: 'wholesale_price',
      stock_quantity: 'stock_quantity',
      packaging: 'packaging',
      roast_level: 'roast_level',
      created_at: 'created_at',
      updated_at: 'updated_at'
    }
  },
  exchange_rates: {
    table: 'exchange_rates',
    columns: {
      id: 'id',
      rate: 'rate',
      created_at: 'created_at',
      updated_at: 'updated_at'
    }
  }
}

// Migration SQL for Supabase
export const SUPABASE_MIGRATIONS = [
  // Create products table
  `
    CREATE TABLE IF NOT EXISTS products (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name_ar TEXT NOT NULL,
      barcode TEXT UNIQUE,
      category TEXT,
      wholesale_price DECIMAL(10,2) DEFAULT 0,
      stock_quantity INTEGER DEFAULT 0,
      packaging TEXT,
      roast_level TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    );
    
    CREATE INDEX IF NOT EXISTS idx_products_barcode ON products(barcode);
    CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
  `,
  
  // Create exchange_rates table
  `
    CREATE TABLE IF NOT EXISTS exchange_rates (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      rate DECIMAL(15,2) NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    );
  `,
  
  // Enable RLS (Row Level Security)
  `
    ALTER TABLE products ENABLE ROW LEVEL SECURITY;
    ALTER TABLE exchange_rates ENABLE ROW LEVEL SECURITY;
    
    -- Allow all operations for authenticated users
    CREATE POLICY "Enable all operations for authenticated users" ON products
      FOR ALL USING (auth.role() = 'authenticated');
    
    CREATE POLICY "Enable all operations for authenticated users" ON exchange_rates
      FOR ALL USING (auth.role() = 'authenticated');
  `
]
